/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AddFarmStatusModel: typeof import('./src/components/AddFarmStatusModel.vue')['default']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    ComfirmOTP: typeof import('./src/components/ComfirmOTP.vue')['default']
    CreateFarmer: typeof import('./src/components/CreateFarmer.vue')['default']
    CreateFarmerForm: typeof import('./src/components/CreateFarmerForm.vue')['default']
    CreateSupplier: typeof import('./src/components/CreateSupplier.vue')['default']
    CreateVeternary: typeof import('./src/components/CreateVeternary.vue')['default']
    CreateVeternaryForm: typeof import('./src/components/CreateVeternaryForm.vue')['default']
    FarmerContract: typeof import('./src/components/FarmerContract.vue')['default']
    FarmerCreateCompletion: typeof import('./src/components/farmer-create-completion.vue')['default']
    FoodRequestModal: typeof import('./src/components/FoodRequestModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Logo: typeof import('./src/components/logo.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
    UpdateSupplier: typeof import('./src/components/UpdateSupplier.vue')['default']
    UpdateVeternary: typeof import('./src/components/UpdateVeternary.vue')['default']
  }
}
